import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Bell,
  BellOff,
  BellRing,
  Binary,
  Bot,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronUp,
  Clipboard,
  Copy,
  CornerUpLeft,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileCog,
  FileImage,
  FileKey,
  FileMusic,
  FileSpreadsheet,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileVideoCamera,
  Fingerprint,
  Flame,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  Home,
  ImageOff,
  ImagePlus,
  KeyRound,
  Laptop,
  LayoutTemplate,
  List,
  Loader2,
  Lock,
  LockOpen,
  LogOut,
  type LucideIcon,
  Mail,
  Maximize2,
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Network,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PlugZap,
  Plus,
  Presentation,
  Radio,
  RadioTower,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Search,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Skull,
  Smartphone,
  SquareTerminal,
  Sun,
  Terminal,
  Trash2,
  Type,
  Unlink,
  Unplug,
  Upload,
  User,
  UserRound,
  Volume2,
  Wrench,
  X,
  Zap,
} from "lucide-react-native";
import { View } from "react-native";

import { type Colors, useTheme } from "@/theme";

export const iconSet = {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Bell,
  BellOff,
  BellRing,
  Binary,
  Bot,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsDownUp,
  ChevronUp,
  Clipboard,
  Copy,
  CornerUpLeft,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCode,
  FileCog,
  FileImage,
  FileKey,
  FileMusic,
  FileSpreadsheet,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileVideoCamera,
  Fingerprint,
  Flame,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  Home,
  ImageOff,
  ImagePlus,
  KeyRound,
  Laptop,
  LayoutTemplate,
  List,
  Loader2,
  Lock,
  LockOpen,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  MessageCircleQuestion,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  Moon,
  MoreHorizontal,
  Network,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PlugZap,
  Plus,
  Presentation,
  Radio,
  RadioTower,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Search,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Settings2,
  Shapes,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Skull,
  Smartphone,
  SquareTerminal,
  Sun,
  Terminal,
  Trash2,
  Type,
  Unlink,
  Unplug,
  Upload,
  User,
  UserRound,
  Volume2,
  Wrench,
  X,
  Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconSet;

export interface IconProps {
  accessibilityLabel?: string;
  color?: keyof Colors;
  name: IconName;
  size?: number;
  testID?: string;
}

export function Icon({ accessibilityLabel, color = "foreground", name, size, testID }: IconProps) {
  const theme = useTheme();
  const IconGlyph = iconSet[name];
  const resolvedSize = size ?? theme.space(4);

  return (
    <View
      accessibilityElementsHidden={accessibilityLabel === undefined}
      accessibilityRole={accessibilityLabel === undefined ? undefined : "image"}
      accessible={accessibilityLabel !== undefined}
      style={{ height: resolvedSize, width: resolvedSize }}
      {...(accessibilityLabel === undefined ? {} : { accessibilityLabel })}
      {...(testID === undefined ? {} : { testID })}
    >
      <IconGlyph
        accessibilityElementsHidden
        accessible={false}
        color={theme.colors[color]}
        size={resolvedSize}
      />
    </View>
  );
}
