import type { CodeLanguage, FileIconId, PreviewKind } from "@/components/files/types";

export interface FileKindEntry {
  kind: PreviewKind;
  label: string;
  mime: string;
  icon: FileIconId;
  language?: CodeLanguage;
  autoBytes?: number;
  maxBytes?: number;
  executable?: boolean;
}

const MEDIA_MAX = 512 * 1024 * 1024;

const code = (label: string, language: CodeLanguage, icon: FileIconId = "code"): FileKindEntry => ({
  kind: "code",
  label,
  mime: "text/plain",
  icon,
  language,
});
const image = (label: string, mime: string): FileKindEntry => ({
  kind: "image",
  label,
  mime,
  icon: "image",
});
const video = (label: string, mime: string): FileKindEntry => ({
  kind: "video",
  label,
  mime,
  icon: "video",
  maxBytes: MEDIA_MAX,
});
const audio = (label: string, mime: string): FileKindEntry => ({
  kind: "audio",
  label,
  mime,
  icon: "audio",
  maxBytes: MEDIA_MAX,
});
const quicklook = (
  label: string,
  icon: FileIconId,
  mime = "application/octet-stream",
): FileKindEntry => ({ kind: "quicklook", label, mime, icon });
const opaque = (label: string, icon: FileIconId, executable = false): FileKindEntry => ({
  kind: "none",
  label,
  mime: "application/octet-stream",
  icon,
  ...(executable ? { executable: true } : {}),
});

export const WHOLE_NAME: Readonly<Record<string, FileKindEntry>> = {
  dockerfile: code("Dockerfile", "shell", "terminal"),
  containerfile: code("Containerfile", "shell", "terminal"),
  makefile: code("Makefile", "shell", "terminal"),
  justfile: code("Justfile", "shell", "terminal"),
  rakefile: code("Rakefile", "shell", "terminal"),
  gemfile: code("Gemfile", "shell", "terminal"),
  procfile: code("Procfile", "shell", "terminal"),
  "cmakelists.txt": code("CMake script", "shell", "terminal"),
  license: { kind: "text", label: "License", mime: "text/plain", icon: "text" },
  notice: { kind: "text", label: "Notice", mime: "text/plain", icon: "text" },
  readme: { kind: "text", label: "Readme", mime: "text/plain", icon: "text" },
  authors: { kind: "text", label: "Authors", mime: "text/plain", icon: "text" },
  ".gitignore": code("Git ignore rules", "shell", "config"),
  ".gitattributes": code("Git attributes", "shell", "config"),
  ".dockerignore": code("Docker ignore rules", "shell", "config"),
  ".editorconfig": code("EditorConfig", "toml", "config"),
  ".npmrc": code("npm config", "toml", "config"),
  ".nvmrc": code("Node version", "plain", "config"),
  ".prettierrc": code("Prettier config", "json", "config"),
  ".babelrc": code("Babel config", "json", "config"),
  ".bashrc": code("Bash startup file", "shell", "terminal"),
  ".zshrc": code("Zsh startup file", "shell", "terminal"),
  ".profile": code("Shell profile", "shell", "terminal"),
  ".ds_store": opaque("Finder metadata", "binary"),
  ".localized": opaque("Localization marker", "binary"),
};

export const COMPOUND: ReadonlyArray<readonly [string, FileKindEntry]> = [
  [".d.ts", code("TypeScript declarations", "ts")],
  [".min.js", code("Minified JavaScript", "js")],
  [".min.css", code("Minified stylesheet", "css")],
  [".tar.gz", opaque("Gzipped tar archive", "archive")],
  [".tar.bz2", opaque("Bzip2 tar archive", "archive")],
  [".tar.xz", opaque("XZ tar archive", "archive")],
  [".tar.zst", opaque("Zstd tar archive", "archive")],
];

export const BY_EXTENSION: Readonly<Record<string, FileKindEntry>> = {
  png: image("PNG image", "image/png"),
  jpg: image("JPEG image", "image/jpeg"),
  jpeg: image("JPEG image", "image/jpeg"),
  gif: image("GIF image", "image/gif"),
  webp: image("WebP image", "image/webp"),
  bmp: image("Bitmap image", "image/bmp"),
  ico: image("Icon", "image/x-icon"),
  avif: image("AVIF image", "image/avif"),
  apng: image("Animated PNG", "image/apng"),
  heic: quicklook("HEIC image", "image", "image/heic"),
  heif: quicklook("HEIF image", "image", "image/heif"),
  tif: quicklook("TIFF image", "image", "image/tiff"),
  tiff: quicklook("TIFF image", "image", "image/tiff"),
  svg: { kind: "svg", label: "SVG image", mime: "image/svg+xml", icon: "vector" },
  ai: quicklook("Illustrator artwork", "vector"),
  eps: quicklook("EPS artwork", "vector"),
  sketch: quicklook("Sketch document", "vector"),
  fig: quicklook("Figma document", "vector"),
  psd: quicklook("Photoshop document", "image"),
  afdesign: quicklook("Affinity Designer document", "vector"),
  afphoto: quicklook("Affinity Photo document", "image"),
  pdf: {
    kind: "pdf",
    label: "PDF document",
    mime: "application/pdf",
    icon: "pdf",
    maxBytes: 128 * 1024 * 1024,
  },
  doc: quicklook("Word document", "doc"),
  docx: quicklook("Word document", "doc"),
  rtf: quicklook("Rich text document", "doc"),
  odt: quicklook("OpenDocument text", "doc"),
  pages: quicklook("Pages document", "doc"),
  xls: quicklook("Excel spreadsheet", "sheet"),
  xlsx: quicklook("Excel spreadsheet", "sheet"),
  ods: quicklook("OpenDocument spreadsheet", "sheet"),
  numbers: quicklook("Numbers spreadsheet", "sheet"),
  ppt: quicklook("PowerPoint presentation", "slides"),
  pptx: quicklook("PowerPoint presentation", "slides"),
  odp: quicklook("OpenDocument presentation", "slides"),
  key: quicklook("Keynote presentation", "slides"),
  epub: quicklook("EPUB book", "doc"),
  mp4: video("MPEG-4 video", "video/mp4"),
  m4v: video("MPEG-4 video", "video/mp4"),
  mov: video("QuickTime movie", "video/quicktime"),
  webm: video("WebM video", "video/webm"),
  ogv: video("Ogg video", "video/ogg"),
  mkv: video("Matroska video", "video/x-matroska"),
  avi: video("AVI video", "video/x-msvideo"),
  wmv: video("Windows Media video", "video/x-ms-wmv"),
  flv: video("Flash video", "video/x-flv"),
  mp3: audio("MP3 audio", "audio/mpeg"),
  m4a: audio("MPEG-4 audio", "audio/mp4"),
  aac: audio("AAC audio", "audio/aac"),
  wav: audio("WAV audio", "audio/wav"),
  flac: audio("FLAC audio", "audio/flac"),
  ogg: audio("Ogg audio", "audio/ogg"),
  oga: audio("Ogg audio", "audio/ogg"),
  opus: audio("Opus audio", "audio/ogg"),
  aiff: audio("AIFF audio", "audio/aiff"),
  aif: audio("AIFF audio", "audio/aiff"),
  md: { kind: "markdown", label: "Markdown", mime: "text/markdown", icon: "markdown" },
  markdown: { kind: "markdown", label: "Markdown", mime: "text/markdown", icon: "markdown" },
  mdx: { kind: "markdown", label: "MDX", mime: "text/markdown", icon: "markdown" },
  txt: { kind: "text", label: "Plain text", mime: "text/plain", icon: "text" },
  log: { kind: "text", label: "Log file", mime: "text/plain", icon: "text" },
  // One JSON object per line — agent transcripts, event logs. Read as text
  // rather than highlighted: a single line can run to hundreds of kilobytes.
  jsonl: { kind: "text", label: "JSON Lines", mime: "text/plain", icon: "text" },
  ndjson: { kind: "text", label: "JSON Lines", mime: "text/plain", icon: "text" },
  csv: { kind: "text", label: "CSV data", mime: "text/csv", icon: "sheet" },
  tsv: { kind: "text", label: "TSV data", mime: "text/tab-separated-values", icon: "sheet" },
  html: code("HTML source", "xml"),
  htm: code("HTML source", "xml"),
  xhtml: code("XHTML source", "xml"),
  xml: code("XML", "xml"),
  plist: code("Property list", "xml", "config"),
  svgz: opaque("Compressed SVG", "vector"),
  js: code("JavaScript", "js"),
  mjs: code("JavaScript module", "js"),
  cjs: code("CommonJS module", "js"),
  jsx: code("JavaScript (JSX)", "jsx"),
  ts: code("TypeScript", "ts"),
  tsx: code("TypeScript (JSX)", "jsx"),
  json: code("JSON", "json", "config"),
  jsonc: code("JSON with comments", "json", "config"),
  json5: code("JSON5", "json", "config"),
  yaml: code("YAML", "yaml", "config"),
  yml: code("YAML", "yaml", "config"),
  toml: code("TOML", "toml", "config"),
  ini: code("INI config", "toml", "config"),
  conf: code("Config file", "toml", "config"),
  cfg: code("Config file", "toml", "config"),
  env: code("Environment file", "shell", "config"),
  css: code("Stylesheet", "css"),
  scss: code("Sass stylesheet", "css"),
  sass: code("Sass stylesheet", "css"),
  less: code("Less stylesheet", "css"),
  py: code("Python", "python"),
  pyi: code("Python stubs", "python"),
  rb: code("Ruby", "c-like"),
  rs: code("Rust", "rust"),
  go: code("Go", "go"),
  c: code("C", "c-like"),
  h: code("C header", "c-like"),
  cc: code("C++", "c-like"),
  cpp: code("C++", "c-like"),
  cxx: code("C++", "c-like"),
  hpp: code("C++ header", "c-like"),
  m: code("Objective-C", "c-like"),
  mm: code("Objective-C++", "c-like"),
  swift: code("Swift", "c-like"),
  java: code("Java", "c-like"),
  kt: code("Kotlin", "c-like"),
  scala: code("Scala", "c-like"),
  php: code("PHP", "c-like"),
  pl: code("Perl", "c-like"),
  lua: code("Lua", "c-like"),
  r: code("R", "c-like"),
  dart: code("Dart", "c-like"),
  ex: code("Elixir", "c-like"),
  exs: code("Elixir script", "c-like"),
  erl: code("Erlang", "c-like"),
  hs: code("Haskell", "c-like"),
  zig: code("Zig", "c-like"),
  sql: code("SQL", "sql", "database"),
  graphql: code("GraphQL", "c-like"),
  gql: code("GraphQL", "c-like"),
  proto: code("Protocol buffers", "c-like"),
  diff: code("Diff", "plain"),
  patch: code("Patch", "plain"),
  sh: { ...code("Shell script", "shell", "terminal"), executable: true },
  bash: { ...code("Bash script", "shell", "terminal"), executable: true },
  zsh: { ...code("Zsh script", "shell", "terminal"), executable: true },
  fish: { ...code("Fish script", "shell", "terminal"), executable: true },
  ps1: { ...code("PowerShell script", "shell", "terminal"), executable: true },
  bat: { ...code("Batch file", "shell", "terminal"), executable: true },
  cmd: { ...code("Batch file", "shell", "terminal"), executable: true },
  zip: opaque("Zip archive", "archive"),
  tar: opaque("Tar archive", "archive"),
  gz: opaque("Gzip archive", "archive"),
  bz2: opaque("Bzip2 archive", "archive"),
  xz: opaque("XZ archive", "archive"),
  zst: opaque("Zstd archive", "archive"),
  "7z": opaque("7-Zip archive", "archive"),
  rar: opaque("RAR archive", "archive"),
  dmg: quicklook("Disk image", "archive"),
  iso: opaque("Disk image", "archive"),
  pkg: opaque("Installer package", "archive", true),
  deb: opaque("Debian package", "archive"),
  rpm: opaque("RPM package", "archive"),
  exe: opaque("Windows executable", "binary", true),
  dll: opaque("Windows library", "binary", true),
  so: opaque("Shared library", "binary", true),
  dylib: opaque("Shared library", "binary", true),
  o: opaque("Object file", "binary"),
  a: opaque("Static library", "binary"),
  wasm: opaque("WebAssembly module", "binary"),
  class: opaque("Java class", "binary"),
  jar: opaque("Java archive", "archive", true),
  pyc: opaque("Python bytecode", "binary"),
  app: opaque("Application bundle", "binary", true),
  command: opaque("Shell command file", "terminal", true),
  workflow: opaque("Automator workflow", "binary", true),
  scpt: opaque("AppleScript", "binary", true),
  webloc: opaque("Web location", "config", true),
  inetloc: opaque("Internet location", "config", true),
  fileloc: opaque("File location", "config", true),
  url: opaque("URL shortcut", "config", true),
  lnk: opaque("Windows shortcut", "config", true),
  pem: code("PEM certificate", "plain", "key"),
  crt: opaque("Certificate", "key"),
  cer: opaque("Certificate", "key"),
  pub: code("Public key", "plain", "key"),
  keychain: opaque("Keychain", "key"),
  ttf: quicklook("TrueType font", "font", "font/ttf"),
  otf: quicklook("OpenType font", "font", "font/otf"),
  woff: quicklook("Web font", "font", "font/woff"),
  woff2: quicklook("Web font", "font", "font/woff2"),
  db: opaque("Database", "database"),
  sqlite: opaque("SQLite database", "database"),
  sqlite3: opaque("SQLite database", "database"),
};

export const UNKNOWN_FILE: FileKindEntry = {
  kind: "quicklook",
  label: "File",
  mime: "application/octet-stream",
  icon: "file",
};

export const DOC_PREFIXES: ReadonlyArray<readonly [string, string]> = [
  ["readme", "Readme"],
  ["license", "License"],
  ["licence", "Licence"],
  ["copying", "License"],
  ["notice", "Notice"],
  ["authors", "Authors"],
  ["contributors", "Contributors"],
  ["contributing", "Contributing guide"],
  ["changelog", "Changelog"],
  ["changes", "Changelog"],
  ["codeowners", "Code owners"],
  ["security", "Security policy"],
  ["todo", "To-do"],
  ["version", "Version"],
];
