import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const workerDir = dirname(fileURLToPath(import.meta.url));
const mobileRoot = resolve(workerDir, "../../..");
const repoRoot = resolve(mobileRoot, "..");

const vendorFiles = [
  "web/node_modules/@xterm/xterm/lib/xterm.js",
  "web/node_modules/@xterm/addon-fit/lib/addon-fit.js",
  "web/node_modules/@xterm/addon-unicode11/lib/addon-unicode11.js",
  "web/node_modules/@xterm/addon-web-links/lib/addon-web-links.js",
  "web/node_modules/@xterm/addon-clipboard/lib/addon-clipboard.js",
  "web/node_modules/@xterm/addon-serialize/lib/addon-serialize.js",
  "web/node_modules/@xterm/addon-webgl/lib/addon-webgl.js",
];

const runtimeFiles = [
  "worker-runtime.js",
  "worker-session.js",
  "worker-host.js",
  "worker-transport.js",
];

const [xtermCss, vendorSources, runtimeSources] = await Promise.all([
  readFile(resolve(repoRoot, "web/node_modules/@xterm/xterm/css/xterm.css"), "utf8"),
  Promise.all(vendorFiles.map((file) => readFile(resolve(repoRoot, file), "utf8"))),
  Promise.all(runtimeFiles.map((file) => readFile(resolve(workerDir, file), "utf8"))),
]);

const scripts = [...vendorSources, ...runtimeSources]
  .join("\n")
  .replaceAll("</script", "<\\/script");

const html = `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<base href="https://spawn.local/">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; img-src data:; font-src 'none'; base-uri 'none'; form-action 'none'">
<style>${xtermCss}
html,body,#terminal{position:fixed;inset:0;width:100%;height:100%;margin:0;padding:0;overflow:hidden;touch-action:none;-webkit-text-size-adjust:none}body{overscroll-behavior:none}
/* A gutter either side so the first column does not sit on the bezel. FitAddon
   subtracts this element's horizontal padding, so the grid still fits exactly. */
.xterm{height:100%;padding:0 8px}
/* Scrolling is driven from the worker, not the browser: nothing here may pan
   on its own or the two would fight. */
.xterm-viewport{touch-action:none;overscroll-behavior:contain}
/* Selection belongs to the system, not to us. xterm ships \`user-select: none\`
   because on a desktop it draws its own selection over a canvas; the DOM renderer
   puts real text in the document instead, so iOS can put its own handles,
   magnifier and Copy/Look Up callout on it — which is what holding text is
   supposed to do. Only the rows opt in: the helper textarea and the cursor layer
   must stay untouchable, or a hold would catch those instead of the output. */
.xterm .xterm-screen,.xterm .xterm-rows,.xterm .xterm-rows *{user-select:text;-webkit-user-select:text;-ms-user-select:text;-webkit-touch-callout:default}
.xterm .xterm-helpers,.xterm .xterm-helper-textarea,.xterm .xterm-cursor-layer{user-select:none;-webkit-user-select:none}</style>
</head>
<body><div id="terminal" role="application" aria-label="Terminal"></div><script>${scripts}</script></body>
</html>`;

await Promise.all([
  writeFile(resolve(mobileRoot, "assets/terminal/worker.html"), html),
  writeFile(
    resolve(workerDir, "worker-html.ts"),
    `// Generated by: node src/terminal/worker/build-worker.mjs\n// biome-ignore-all lint/suspicious/noTemplateCurlyInString: bundled vendor source\n// biome-ignore format: bundled vendor source\nexport const TERMINAL_WORKER_HTML = ${JSON.stringify(html)};\n`,
  ),
]);

console.log(`Generated terminal worker (${Buffer.byteLength(html)} bytes).`);
